name: App build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup dependencies
        run: npm install

      - name: Run Build for macOS
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          GOOGLE_SCOPES: ${{ secrets.GOOGLE_SCOPES }}
        run: npm run transpile:electron && npm run build && npx electron-builder --mac --x64 --publish=always

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup dependencies
        run: npm install

      - name: Run Build for Windows
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          GOOGLE_SCOPES: ${{ secrets.GOOGLE_SCOPES }}
        run: npm run transpile:electron && npm run build && npx electron-builder --win --x64 --publish=always
